server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
              - Path=/posts/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/user/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

security:
  jwt:
    secret-key: 56uewfjwbvqebf38ry32rejwfbf139f18h3eufwef

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
