server:
  port: 8084

logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG

spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: YOUR_API_KEY_HERE
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash-exp

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
